- name: this a filter
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: enter the number
    private: false
  tasks:
  - name: print if less than
    when: number =< 10 #this is a integer
    ansible.builtin.debug:
      msg: "this a filter and show {{number}}"
    