- name: this a filter
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: enter the number
    private: false
  tasks:
  - name: it is a filter
    ansible.builtin.debug:
      msg: "this a filter and show {{number}}"
    when: number < 10 #this is a integer