- name: this a filter
  hosts: local
  connection: local
  vars_prompt:
  - name: int_number
    prompt: enter the number
    private: false
  tasks:
  - name: print if less than
    ansible.builtin.debug:
      msg: "this a filter and show {{int_number}}"
    when: int_number < 10 #this is a integer