- name: functions and their uses
  hosts: BAS
  become: yes #kpkpkpk
  tasks: 
  - name : install nginx
    ansibe.builtin.package:
     name: nginx
     state : present
  
  - name: enable nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enable: yes