- name: functions and their uses
  hosts: BAS
  become: yes
  tasks: 
  - name: nginx
    ansibe.inbuilt.package:
     status: present
  - name: enable nginx
    ansible.inbuilt.service:
     enable: yes