- name: infrastructure
  hosts: sega
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
      msg: "nginx installation"

  # - name: enable nginx
  #   ansible.builtin.service:
  #     name: nginx
  #     state: started
  #     enabled: yes