- name: play level variables
  hosts: sega
  
  tasks:
  - name: play level tasks
    vars:
    - course: "cloud engine"
    - material: "online class"
    - systems: "cloud servers"
    ansible.builtin.debug:
     msg: featuring {{course}}, {{material}}, {{systems}}