- name: segment
  hosts: sega
  tasks:
  - name: this a addition
    ansible.builtin.debug:
     msg: "addition={{10+10}}"
  - name: this is multiplication
    ansible.builtin.debug:
     msg: "multiplication={{10*2}}"